#!/bin/bash

if [ -d _pkg ]
then
    echo _pkg already exists. Please delete it.
    exit 1
fi

mkdir _pkg
for f in src css res background.html options.html manifest.json
do
    cp -R $f _pkg
done
cd _pkg

# Add `-w` and run the following command while developing
coffee -o js src
docco src/api.coffee

rm -Rf src
rm -Rf res/*.xcf

file ../keyboard-fu.zip && rm ../keyboard-fu.zip
zip -r ../keyboard-fu .

cd ..
rm -Rf _pkg
